name: Main

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:40
    permissions:
      contents: write
    steps:
      - run: dnf install -y git
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: dnf install -y expat-devel fontconfig-devel freetype-devel harfbuzz-devel brotli-devel
      - run: dnf install -y libicu-devel libjpeg-turbo-devel libwebp-devel libxml2-devel mesa-libGL-devel vulkan-headers
      - run: dnf install -y clang git patch time zip python-unversioned-command ninja-build
      - run: dnf install -y cmake chrpath autoconf
      - run: ./00_apply-patches.sh
      - run: ./01_build-skia.sh
      - run: ./02_build-svg-native-viewer.sh
      - run: ./03_build-freetype2.sh
      - run: ./04_build-freetype2-demo.sh
